---
- name: Restart apache servers
  hosts: webservers
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: Restart Apache Service
      ansible.builtin.systemd:
        name: httpd
        state: restarted